[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
{% if std -%}
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }
{% if hal == "Yes (default features)" -%}
esp-idf-hal = { version = "0.40.1"}
esp-idf-svc = { version = "0.45.0"}
{%- elsif hal == "Yes (all features)" -%}
esp-idf-hal = { version = "0.40.1", features = [
    "default",
    "embassy-sync",
    "critical-section",
    "edge-executor"
]}
esp-idf-svc = { version = "0.45.0", features = [
    "std",
    "nightly",
    "experimental",
    "embassy-time-driver",
    "embassy-time-isr-queue",
    "alloc"
]}
{%- endif %}
{%- else -%}
log = { version = "0.4.17", default-features = false }
esp-idf-sys = { version = "0.32.1", default-features = false, features = ["binstart", "panic_handler", "alloc_handler"] }
esp-idf-svc = { version = "0.45.0", default-features = false, features = ["alloc"] }
{%- endif %}

[build-dependencies]
embuild = "0.31.1"

{% if espidfver != "v4.4" or hal == "Yes (all features)" -%}
# v5.0 and master require patches due to https://github.com/esp-rs/esp-idf-template/issues/91#issuecomment-1508241327
[patch.crates-io]
esp-idf-hal = { git="https://github.com/esp-rs/esp-idf-hal"}
esp-idf-svc = { git="https://github.com/esp-rs/esp-idf-svc"}
{%- endif %}
{% if hal == "Yes (all features)" -%}
embedded-svc = { git = "https://github.com/esp-rs/embedded-svc" }
{%- endif %}