name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 7 * * *'

env:
  rust_toolchain: nightly

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Setup | Std
        run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default ${{ env.rust_toolchain }}
      - name: Setup | cargo-generate
        run: cargo install cargo-generate
      - name: Setup | ldproxy
        run: cargo install ldproxy
      - name: (STD, PIO) Generate
        run: cargo generate --git https://github.com/ivmarkov/esp-idf-template cargo --name test --vcs none --silent -d mcu=esp32c3 -d toolchain=nightly -d std=true -d espidfver=v4.3.2
      - name: (STD, PIO) Build | Fmt Check
        run: cd test; cargo fmt -- --check
      - name: (STD, PIO) Build | Clippy
        run: cd test; cargo clippy --no-deps -- -Dwarnings
      - name: (STD, PIO) Build | Compile
        run: cd test; cargo build
      - name: (NOSTD, NATIVE, V4.4) Generate
        run: cargo generate --git https://github.com/ivmarkov/esp-idf-template cargo --name testnostd --vcs none --silent -d mcu=esp32c3 -d toolchain=nightly -d std=false -d espidfver=v4.4
      - name: (NOSTD, NATIVE, V4.4) Build | Fmt Check
        run: cd testnostd; cargo fmt -- --check
      - name: (NOSTD, NATIVE, V4.4) Build | Clippy
        run: cd testnostd; cargo clippy --no-deps -- -Dwarnings
      - name: (NOSTD, NATIVE, V4.4) Build | Compile
        run: cd testnostd; cargo build --features native
      - name: (STD, CMake, V4.4) Generate
        run: cargo generate --git https://github.com/ivmarkov/esp-idf-template cmake --name testidf --vcs none --silent -d toolchain=nightly -d std=true -d espidfver=v4.4
      - name: (STD, CMake, V4.4) ESP-IDF | Checkout
        run: git clone https://github.com/espressif/esp-idf; git -C esp-idf checkout release/v4.4
      - name: (STD, CMake, V4.4) ESP-IDF | Install Tooling
        run: esp-idf/install.sh
      - name: (STD, CMake, V4.4) Build | Set Target
        run: . esp-idf/export.sh; cd testidf; idf.py set-target esp32c3
      - name: (STD, CMake, V4.4) Build | Compile
        run: . esp-idf/export.sh; cd testidf; idf.py build
